import UserResolvers from './user';
import MutationResolvers from './mutation';
import QueryResolvers from './query';
import { Resolvers } from '../generated';

// Stop using our own typings and use the ones
// generated by codegen since i got
// it to work with federation

const resolvers: {
  [T in keyof Resolvers]:
    | typeof QueryResolvers
    | typeof MutationResolvers
    | typeof UserResolvers;
} = {
  Query: QueryResolvers,
  Mutation: MutationResolvers,
  User: UserResolvers,
};

export default resolvers;
